#--------------------------------------
# 菜单配置说明
# identifier ： 唯一标识不可重复
# name       ： 菜单显示名称
# pageref    ： 本站点链接地址，与 URL 选其一
# url        ： 站点外部链接地址，以 http 或者 https 开头
# pre        ： 菜单小图标
# weight     ： 显示顺序，字数越小越靠前
# 
# Menus Settings
# identifier : Unique ID cannot be repeated
# name       : Menu name
# pageref    : Link of webiste and not appeare same time with url
# url        : Exteneral link out of website and start with http or https
# pre        : Icon of menu
# weight     : Order number and smaller is top
# -------------------------------------
main:
  - identifier: home
    name: 首页
    pageref: /
    pre: home
    weight: 1
  - identifier: about
    name: 关于
    pageref: /about.html
    pre: user
    weight: 2
  - identifier: archives
    name: 归档
    pageref: /archives
    pre: archive
    weight: 3
  - identifier: tags
    name: 标签
    pageref: /tags
    pre: tags
    weight: 4
  - identifier: dev
    name: 文章 - 开发笔记/心得
    pageref: /categories/dev
    pre: laptop
    weight: 5
  - identifier: Life
    name: 文章 - 生活
    pageref: /categories/life
    pre: star-of-life
    weight: 6
  - identifier: Study
    name: 文章 - 学习
    pageref: /categories/study
    pre: book
    weight: 7
  - identifier: Game
    name: 文章 - 游戏
    pageref: /categories/game
    pre: gamepad
    weight: 8
  - identifier: ai
    name: 文章 - AI
    pageref: /categories/ai
    pre: brain
    weight: 9
  - identifier: Showcase
    name: 展示柜 Showcase
    pageref: /categories/showcase
    pre: inbox
    weight: 10
  - identifier: site
    name: 建站心得
    pageref: /categories/site
    pre: sitemap
    weight: 11
  - identifier: flinks
    name: 友情链接
    pageref: /flinks.html
    pre: thumbs-up
    weight: 12